# Esse arquivo é de deployment referente ao backend que leva as capas dos livros
# Deployments gerenciam pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-capas-livros
  labels:
    app: backend-capas-livros
spec:
  selector:
    matchLabels:
      app: backend-capas-livros
  template:
    metadata:
      labels:
        app: backend-capas-livros
    spec:
      containers:
        - name: backend-capas-livros
          image: capas
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "200m"