services:
  mysql:
    image: db
    restart: always
    container_name: mysql
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
  
  tomcat:
    image: web
    container_name: tomcat
    env_file:
      - .env    
    ports:
      - "8080:8080"
    volumes:
      - ./target/Livraria.war:/usr/local/tomcat/webapps/Livraria.war
    depends_on:
      - mysql
  
  images:
    image: book-covers
    container_name: images_covers
    ports:
      - "8081:80"
    volumes:
      - ./book-covers:/usr/share/nginx/html
    depends_on:
      - tomcat
      - mysql
  