# Esse arquivo é de mapeamento de configurações (configuration map - configmap)
# É um objeto da API usado para armazenar dados NÃO-confidenciais em pares chave-valor 
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: livraria-configmap
data: 
  database_url: jdbc:mysql://livraria-db:3306/Livraria/Livraria?createDatabaseIfNotExist=true
  host: livraria-db