# Esse arquivo é de deployment referente ao banco de dados
# Deployments gerenciam pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livraria-db
  labels:
    app: livraria-db
spec:
  selector:
    matchLabels:
      app: livraria-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: livraria-db
    spec:
      containers:
      - name: livraria-db
        image: db
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: livraria-secret
                key: password
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
          - name: livraria-volumes
            mountPath: /var/lib/mysql
      volumes:
        - name: livraria-volumes
          persistentVolumeClaim:
            claimName: livraria-pv-claim