apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
spec:
  rules:
  - host: Livraria.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-site
            port:
              number: 8080
        capalivro:
          service:
            name: backend-capas-livros
            port:
              number: 8081
