# Esse arquivo é de deployment referente ao site (backend)
# Deployments gerenciam pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-site
  labels:
    app: backend-site
spec:
  selector:
    matchLabels:
      app: backend-site
  template:
    metadata:
      labels:
        app: backend-site
    spec:
      containers:
        - name: backend-site
          image: web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: livraria-configmap
                  key: database_url
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: livraria-configmap
                  key: host
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: livraria-secret
                  key: username
            - name: MYSQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: livraria-secret
                  key: password
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"